module.exports = {
  apps: [
    {
      name: 'prisma-studio',
      script: 'npx',
      args: 'prisma studio',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        PORT: 5555,
        NODE_ENV: 'development',
      },
      error_file: './logs/prisma-studio-error.log',
      out_file: './logs/prisma-studio-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'api-gateway',
      script: 'dist/apps/api-gateway/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        PORT: 3000,
        NODE_ENV: 'development',
      },
      error_file: './logs/api-gateway-error.log',
      out_file: './logs/api-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'user-service',
      script: 'dist/apps/user-service/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        PORT: 3001,
        NODE_ENV: 'development',
      },
      error_file: './logs/user-service-error.log',
      out_file: './logs/user-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'template-service',
      script: 'dist/apps/template-service/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        PORT: 3003,
        NODE_ENV: 'development',
      },
      error_file: './logs/template-service-error.log',
      out_file: './logs/template-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'email-service',
      script: 'dist/apps/email-service/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        PORT: 3002,
        NODE_ENV: 'development',
      },
      error_file: './logs/email-service-error.log',
      out_file: './logs/email-service-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
